### ISSUE TITLE
in graph the new line starts on same level

### ISSUE THREAD

**Issue by alexvz901** [DualzIT/Dashball#2]
Now every time a new dot is created on the graph the line starts on the bottom and moves up. the line needs to start on the same level than the one before or directly to the right place.
![image](https://github.com/alexvz901/Dashball/assets/125699393/d4272563-0c15-4bf3-bdda-c3a8b5563d30)

**Comment by StijnROC** [comment]
Wow! Super opgeschreven Alex!
