### ISSUE TITLE
Configurable features

### ISSUE THREAD

**Issue by StefanZoggel** [DualzIT/Dashball#32]
I want to configure:
1. port (iso 80, might already be in use). How to changed this because UI is not working yet. Config file or form in installation???
2. Config items via UI: Like update speed (complete day visible).
3. Enable/disble graphs
4. ...

**Comment by alexvz901** [comment]
Added config.json. Here you can change the webserver port and the data update speed. 
I created another issue for the complete day visible. 
I also added the port configuration in the .exe installer
![image](https://github.com/DualzIT/Dashball/assets/125699393/d9ba8148-0a0f-4395-bc0a-3708e7d8c758)
